server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${rag.datasource.driver-class-name}
    url: jdbc:mysql://${rag.datasource.host}:${rag.datasource.port}/${rag.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${rag.datasource.username}
    password: ${rag.datasource.password}
  redis:
    host: ${rag.redis.host}
    port: ${rag.redis.port}
#    password: ${sky.redis.password}
    database: ${rag.redis.database}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 0B
  mail:
    host: smtp.qq.com
    port: 465
    username: 1073931273@qq.com
    password: etcwugbbntlkbaeh
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        debug: false
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
        smtp:
          auth: true
          ssl:
            enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vichayturen.rag_chatman.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

rag:
  jwt:
    user-secret-key: vichayturen-vichayturen-vichayturen-vichayturen
    user-ttl: 86400000
    user-token-name: authentication
  llm:
    type: local #local,glm,gpt
    api-key: 123
    model: qwen
    url: http://localhost:1222/chat/stream
  lucene:
    path: ${rag.lucene.path}
  embedding:
    url: http://localhost:1222/embedding
