server:
  port: 8080

spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    mode: LEGACYHTML5
    template-resolver-order: 0
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${rag.datasource.driver-class-name}
    url: jdbc:mysql://${rag.datasource.host}:${rag.datasource.port}/${rag.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${rag.datasource.username}
    password: ${rag.datasource.password}
  redis:
    host: ${rag.redis.host}
    port: ${rag.redis.port}
#    password: ${sky.redis.password}
    database: ${rag.redis.database}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    port: 465
    username: 1073931273@qq.com
    password: wpkefohqoljjbaeh
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vichayturen.rag_chatman.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

rag:
  jwt:
    user-secret-key: vichayturen
    user-ttl: 86400000
    user-token-name: authentication
  llm:
    selected: zhipu
    zhipu:
      api-key: f8d197a3630fbba06bdccbb5f36340fe.qPuVwL0zPHsDOC8S
      model: glm-4
      url: https://open.bigmodel.cn/api/paas/v4/chat/completions
  lucene:
    path: ${rag.lucene.path}
